#!/bin/bash
USAGE="Usage: $0 EMAIL PASSWORD [BASEDIR]";

if [ ! -n "$2" ]
then
    echo $USAGE;
    exit 1;
fi

USERNAME=$(echo "$1" | cut -f1 -d@);
DOMAIN=$(echo "$1" | cut -f2 -d@);
ADDRESS=$1;
PASSWD=$2;

if [ -n "$3" ]
then
    if [ ! -d "$3" ]
    then
        echo $USAGE;
        echo "BASEDIR must be a valid directory!";
        echo "I would have tried, $(postconf | grep ^virtual_mailbox_base | cut -f3 -d' ')";
        exit 2;
    else
        BASEDIR="$3";
    fi
else
    BASEDIR="$(postconf | grep ^virtual_mailbox_base | cut -f3 -d' ')";
fi

if [ -d "$BASEDIR/$DOMAIN/" ]
then
    echo "Updating Dovecot user password..."

    sed -i "/$ADDRESS/c$ADDRESS:$(doveadm pw -p $PASSWD)" $BASEDIR/$DOMAIN/shadow
    chown vmail:vmail $BASEDIR/$DOMAIN/shadow && chmod 775 $BASEDIR/$DOMAIN/shadow

    systemctl restart postfix
    systemctl restart dovecot

    exit 0
else
    exit 3
fi
