INSTALLER_DIRECTORY="$(pwd)"

TMP_PATH=/root/install

WEBPUB_PATH="/var/www"
WEBAPI_PATH="/var/www/station-api"
INBOX_PATH="/var/www/station-api/storage/app/inbox"
WEBGUI_PATH="/var/www/html"
DELTACHAT_DOWNLOAD_PATH="/var/www/html/downloads"
ROUNDCUBE_PATH="/var/www/html/email"


HERMES_DB="hermes"
HERMES_DB_USER="hermes"

# HERMES_HARDENING="true" in a station file turns on the security hardening:
# random per-station passwords (pi, WiFi, databases, mail, VNC), the scoped
# sudo policy, SSH by key only (when conf/ssh/authorized_keys exists), the
# station's own TLS certificate, WPA2/WPA3 WiFi, VNC on localhost and the
# HSTS/CSP web headers.  Off by default, so that a station of a deployed
# network, installed or reinstalled, keeps what the rest of the network
# expects: pi/hermes, the shared WiFi passphrase, the shared certificate.
HERMES_HARDENING="${HERMES_HARDENING:-false}"

# Without HERMES_HARDENING, the credentials an operator or a phone uses to
# reach the station are always the historical ones, whatever the secrets
# file holds: a station installed by the 22-25 Sep installer has random ones
# there, and a reinstall must not change pi's password or the WiFi key under
# a deployed network. Service-internal passwords (databases, mail, API) stay
# as the file has them, since the services on the station already use them.
# The historical values are in conf/legacy-credentials, which only the
# deployments that need them have (see tasks/secrets_setup.sh).
hermes_legacy_credentials()
{
    local legacy="${INSTALLER_DIRECTORY}/conf/legacy-credentials"
    if [ "${HERMES_HARDENING}" != "true" ] && [ -s "${legacy}" ]; then
        eval "$(grep -E '^(PI_PASSWORD|WIFI_PASSPHRASE|VNC_PASSWORD)=' "${legacy}")"
    fi
}

# per-station passwords, generated by do_secrets_setup on the first install
if [ -s /etc/hermes/secrets ]; then
    . /etc/hermes/secrets
fi
hermes_legacy_credentials

# Default to false if DEFAULT_VOICE is unset
DEFAULT_VOICE="${DEFAULT_VOICE:-false}"

# use VARA as default modem if MODEM_TYPE not set
MODEM_TYPE="${MODEM_TYPE:-vara}"

# The program that drives the radio (see tasks/radio_setup.sh):
# sbitx_controller (the default on an sBitx) or radiod (hermes-radio-daemon,
# the only choice for a Hamlib CAT radio, HARDWARE=hamlib).
if [ "${HARDWARE}" = "hamlib" ]; then
    RADIO_CONTROLLER="${RADIO_CONTROLLER:-radiod}"
else
    RADIO_CONTROLLER="${RADIO_CONTROLLER:-sbitx_controller}"
fi

# Branches of hermes-net and hermes-radio-daemon to install, to try one out
# before it is merged; empty means the usual one (hermes-net's nncp-transport
# on an NNCP station, maintenance-debian12 on Debian 12, else the default).
HERMES_NET_BRANCH="${HERMES_NET_BRANCH:-}"
HERMES_RADIO_DAEMON_BRANCH="${HERMES_RADIO_DAEMON_BRANCH:-}"

# HARDWARE=hamlib: the radio, as Hamlib sees it.  RIG_MODEL is the Hamlib
# model number (rigctl -l), e.g. 3070 for the IC-7100.
RIG_MODEL="${RIG_MODEL:-}"
RIG_DEVICE="${RIG_DEVICE:-/dev/ttyUSB0}"
RIG_SERIAL_RATE="${RIG_SERIAL_RATE:-19200}"
RIG_PTT_TYPE="${RIG_PTT_TYPE:-RIG}"
# the rig's USB codec, by ALSA card name so that its index does not matter
RIG_AUDIO_DEVICE="${RIG_AUDIO_DEVICE:-hw:CODEC,0}"

if [ "${HARDWARE}" = "hamlib" ] && [ -z "${RIG_MODEL}" ]; then
    echo "HARDWARE=hamlib needs RIG_MODEL, the Hamlib model number (rigctl -l)."
    exit 1
fi

# The pre-agreed UUCP startup: stations answer with uucpd -F and a gateway
# calls with uucico -Y, which turns the six line turnarounds of the UUCP
# handshake into two.  Both need uucp 1.07-37 or later, which the installer
# builds from Rhizomatica/uucp (branch UUCP_BRANCH) when the installed one is
# older.  A station running uucpd -F still answers callers that do not use
# it, but a caller using -Y cannot reach a station without it.  So it is off
# unless the station file turns it on: reinstalling one station of a
# deployed network must not cut it off from the others.  Turn it on in every
# station file of a network once all its stations have uucp 1.07-37
# (hermes-setup writes it on for new stations).
UUCP_PRE_AGREED="${UUCP_PRE_AGREED:-false}"
UUCP_BRANCH="${UUCP_BRANCH:-master}"

# Default to v1 if DISPLAY_TYPE is unset
DISPLAY_TYPE="${DISPLAY_TYPE:-v1}"

#if [[ $station_name =~ "hermes" ]]; then
#  vpn_file_base=${station_name//./_}
#else
  vpn_file_base=${station_name}
#fi

# run me as root!
if [[ $(id -u) -ne 0 ]];
then
    echo "Please run as root";
    exit 1;
fi

if ! [ -x "$(command -v wget)" ]; then
    echo "Error: wget is not installed. Installing."
    apt-get -y install wget
fi

mkdir -p ${TMP_PATH}

# The station's name before this run: the system task renames it to
# HERMES_HOSTNAME.  A station reinstalled under another name (a remote
# station turned into its network's gateway, say) is the one case where
# the installer switches off what belonged to the old name.
ORIGINAL_HOSTNAME="$(cat /etc/hostname 2> /dev/null || true)"

# determine FIRST_INSTALL if it's not set by the user
FIRST_INSTALL="${FIRST_INSTALL:-}"
if [ -z "${FIRST_INSTALL}" ]; then
  if [ -f /root/hermes-setup-done.txt ]; then
    FIRST_INSTALL="false"
  else
    FIRST_INSTALL="true"
  fi
fi
