#!/bin/sh
vncconfig -iconic &

cp /opt/VARA/VARA.ini.default /opt/VARA/VARA.ini

# remove .wine directory to prevent corruption
#rm -rf /root/.wine
# and copy our defaults?


# run VARA
/usr/bin/xterm -bg black -fg green -e wine /opt/VARA/VARA.exe &

# run UHRR
# su hermes -c "cd /opt/uhrr; /usr/bin/xterm -bg gray50 -fg white -e /opt/uhrr/UHRR &" </home/hermes/key

/usr/bin/wmaker
#xrdb $HOME/.Xresources
